service: product-service

plugins:
  - serverless-auto-swagger
  - serverless-bundle
  - serverless-offline

custom:
  bundle:
    ignorePackages:
      - pg-native

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  stage: dev
  httpApi:
    cors:
      allowedOrigins:
        - https://dv0irgcfxah3p.cloudfront.net
      allowedHeaders:
        - Content-Type
        - Authorization
      allowedMethods:
        - GET
        - POST

functions:
  getProductsList:
    handler: handler.getProductsList
    events:
      - http:
          path: products
          method: get
          cors: true
          responses:
            200:
              description: 'Successful product list response'
              bodyType: 'ProductList'
  getProductsById:
    handler: handler.getProductsById
    events:
      - http:
          path: products/{id}
          method: get
          request:
            parameters:
              paths:
                id: true
          cors: true
          responses:
            200:
              description: 'Successful Product response'
              bodyType: 'Product'
            404:
              description: 'Not found'
  createNewProduct:
    handler: handler.createNewProduct
    events:
      - http:
          path: products
          method: post
          cors: true
          bodyType: 'Product'
          responses:
            201:
              description: 'Successful Product response'
              bodyType: 'ProductList'
